import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowRight, Compass, Scale, ShieldCheck, RefreshCcw } from "lucide-react";
import { dimensionsQuery } from "@/lib/queries";
import { ScoreRing } from "@/components/score/ScoreRing";

export const Route = createFileRoute("/score")({
  loader: ({ context }) => {
    context.queryClient.ensureQueryData(dimensionsQuery);
  },
  head: () => ({
    meta: [
      { title: "How the Biosphere Score works — Isle of Man Biosphere" },
      { name: "description", content: "The Biosphere Score is a weighted 0–100 rating generated by the Biosphere Compass, based on the Isle of Man Climate Impact Assessment framework." },
      { property: "og:title", content: "How the Biosphere Score works" },
      { property: "og:description", content: "A weighted 0–100 sustainability rating from the Biosphere Compass." },
    ],
  }),
  errorComponent: ({ error }) => (
    <div role="alert" className="mx-auto max-w-2xl px-4 py-20 text-center text-muted-foreground">{error.message}</div>
  ),
  notFoundComponent: () => <div className="px-4 py-20 text-center">Page unavailable.</div>,
  component: ScorePage,
});

const BANDS = [
  { range: "90–100", label: "Outstanding", token: "--score-outstanding", blurb: "Sector-leading, independently verified sustainability performance." },
  { range: "75–89", label: "Excellent", token: "--score-excellent", blurb: "Strong, measurable progress embedded across the business." },
  { range: "60–74", label: "Good", token: "--score-good", blurb: "Solid foundations with clear plans and evidence of action." },
  { range: "40–59", label: "Developing", token: "--score-developing", blurb: "On the journey — key practices underway, more to formalise." },
  { range: "Below 40", label: "Beginning", token: "--score-beginning", blurb: "Just getting started, with support available from the Biosphere team." },
];

function ScorePage() {
  const { data: dimensions } = useSuspenseQuery(dimensionsQuery);

  return (
    <div className="mx-auto max-w-5xl px-4 py-14 sm:px-6">
      <div className="text-center">
        <p className="inline-flex items-center gap-2 rounded-full bg-secondary px-4 py-1.5 text-xs font-semibold uppercase tracking-widest text-secondary-foreground">
          <Compass className="h-3.5 w-3.5" aria-hidden /> The Biosphere Compass
        </p>
        <h1 className="mt-4 font-display text-4xl font-semibold sm:text-5xl">How the Biosphere Score works</h1>
        <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
          Every business in the directory is assessed with the Biosphere Compass — our
          proprietary framework built on the Climate Impact Assessment used by the Isle of Man.
          The result is one trusted score out of 100.
        </p>
      </div>

      <div className="mt-14 grid items-center gap-10 lg:grid-cols-[auto_1fr]">
        <div className="mx-auto">
          <ScoreRing score={82} size={200} />
        </div>
        <div className="space-y-3">
          {BANDS.map((b) => (
            <div key={b.label} className="card-soft flex items-center gap-4 p-4">
              <span className="h-4 w-4 shrink-0 rounded-full" style={{ backgroundColor: `var(${b.token})` }} aria-hidden />
              <span className="w-20 shrink-0 text-sm font-bold">{b.range}</span>
              <span className="w-28 shrink-0 text-sm font-semibold">{b.label}</span>
              <span className="hidden text-sm text-muted-foreground sm:block">{b.blurb}</span>
            </div>
          ))}
        </div>
      </div>

      <section className="mt-16" aria-labelledby="dimensions-heading">
        <h2 id="dimensions-heading" className="font-display text-3xl font-semibold">The Compass dimensions</h2>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Each dimension contributes to the overall score according to its weighting. The
          framework is designed to evolve — dimensions, questions and weights are managed by the
          Biosphere team and will grow over time.
        </p>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {dimensions.map((d) => (
            <div key={d.slug} className="card-soft p-5">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">{d.name}</h3>
                <span className="rounded-full bg-secondary px-2 py-0.5 text-[11px] font-bold text-secondary-foreground">
                  ×{Number(d.weight)}
                </span>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">{d.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-16 grid gap-6 sm:grid-cols-3" aria-label="Assessment process">
        {[
          { icon: Scale, title: "Weighted scoring", text: "Each dimension is scored 0–100 from assessment answers, then combined using its weight into the overall Biosphere Score." },
          { icon: ShieldCheck, title: "Evidence & verification", text: "Businesses upload supporting evidence. Scores publish immediately as self-assessed, then the Biosphere team reviews and verifies them." },
          { icon: RefreshCcw, title: "Annual reassessment", text: "Scores stay current — businesses reassess every year to reflect real, ongoing progress." },
        ].map(({ icon: Icon, title, text }) => (
          <div key={title} className="card-soft p-6">
            <span className="inline-flex h-11 w-11 items-center justify-center rounded-xl bg-secondary text-primary">
              <Icon className="h-5 w-5" aria-hidden />
            </span>
            <h3 className="mt-4 font-display text-lg font-semibold">{title}</h3>
            <p className="mt-2 text-sm text-muted-foreground">{text}</p>
          </div>
        ))}
      </section>

      <div className="mt-16 rounded-3xl bg-primary p-10 text-center text-primary-foreground">
        <h2 className="font-display text-2xl font-semibold">Ready to earn your Biosphere Score?</h2>
        <p className="mx-auto mt-2 max-w-xl text-primary-foreground/85">
          Create a free account, complete the Compass assessment and join the Island's most
          trusted sustainability directory.
        </p>
        <Link
          to="/auth"
          className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3 text-sm font-bold text-primary"
        >
          Start your assessment <ArrowRight className="h-4 w-4" aria-hidden />
        </Link>
      </div>
    </div>
  );
}
