import { Link } from "@tanstack/react-router";
import { Leaf } from "lucide-react";

export function SiteFooter() {
  return (
    <footer className="border-t border-border bg-muted/40">
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6">
        <div className="grid gap-10 md:grid-cols-3">
          <div>
            <div className="flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                <Leaf className="h-4 w-4" />
              </span>
              <span className="font-display text-base font-semibold">Biosphere Beacons</span>
            </div>
            <p className="mt-3 max-w-xs text-sm text-muted-foreground">
              The definitive directory of Isle of Man businesses committed to sustainability and
              the UNESCO Biosphere vision.
            </p>
          </div>
          <nav className="text-sm" aria-label="Footer navigation">
            <p className="font-semibold">Explore</p>
            <ul className="mt-3 space-y-2 text-muted-foreground">
              <li><Link to="/directory" className="hover:text-foreground">Business directory</Link></li>
              <li><Link to="/directory" search={{ view: "map" }} className="hover:text-foreground">Interactive map</Link></li>
              <li><Link to="/score" className="hover:text-foreground">How the Biosphere Score works</Link></li>
              <li><Link to="/analytics" className="hover:text-foreground">Island analytics</Link></li>
            </ul>
          </nav>
          <div className="text-sm">
            <p className="font-semibold">For businesses</p>
            <ul className="mt-3 space-y-2 text-muted-foreground">
              <li><Link to="/auth" className="hover:text-foreground">Join the directory</Link></li>
              <li><Link to="/assessment" className="hover:text-foreground">Complete your assessment</Link></li>
            </ul>
          </div>
        </div>
        <p className="mt-10 text-xs text-muted-foreground">
          © {new Date().getFullYear()} Isle of Man Biosphere Business Directory. Scores are
          generated by the Biosphere Beacons, inspired by the Isle of Man Climate Impact
          Assessment framework.
        </p>
      </div>
    </footer>
  );
}
